sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: **
    access-key-secret: **
    bucket-name: cqwm-jack
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxcdf83551b26a1783
    secret: 82fc1418a4588fa4f35e7d82dc4b35ce
  shop:
    address: 武汉市洪山区武汉理工大学马房山校区西院
  baidu:
    ak: **
